// Code generated by skv2. DO NOT EDIT.

// This file contains generated Deepcopy methods for proto-based Spec and Status fields

package types

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto for the ExtAuthConfig.Spec
func (in *ExtAuthConfigSpec) DeepCopyInto(out *ExtAuthConfigSpec) {
	p := proto.Clone(in).(*ExtAuthConfigSpec)
	*out = *p
}

// DeepCopyInto for the ExtAuthConfig.Status
func (in *ExtAuthConfigStatus) DeepCopyInto(out *ExtAuthConfigStatus) {
	p := proto.Clone(in).(*ExtAuthConfigStatus)
	*out = *p
}
