// Code generated by skv2. DO NOT EDIT.

//go:generate mockgen -source ./clients.go -destination mocks/clients.go

package v1alpha1

import (
	"context"

	"github.com/solo-io/skv2/pkg/controllerutils"
	"github.com/solo-io/skv2/pkg/multicluster"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/client-go/kubernetes/scheme"
	"k8s.io/client-go/rest"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// MulticlusterClientset for the extauth.solo.io/v1alpha1 APIs
type MulticlusterClientset interface {
	// Cluster returns a Clientset for the given cluster
	Cluster(cluster string) (Clientset, error)
}

type multiclusterClientset struct {
	client multicluster.Client
}

func NewMulticlusterClientset(client multicluster.Client) MulticlusterClientset {
	return &multiclusterClientset{client: client}
}

func (m *multiclusterClientset) Cluster(cluster string) (Clientset, error) {
	client, err := m.client.Cluster(cluster)
	if err != nil {
		return nil, err
	}
	return NewClientset(client), nil
}

// clienset for the extauth.solo.io/v1alpha1 APIs
type Clientset interface {
	// clienset for the extauth.solo.io/v1alpha1/v1alpha1 APIs
	ExtAuthConfigs() ExtAuthConfigClient
}

type clientSet struct {
	client client.Client
}

func NewClientsetFromConfig(cfg *rest.Config) (Clientset, error) {
	scheme := scheme.Scheme
	if err := AddToScheme(scheme); err != nil {
		return nil, err
	}
	client, err := client.New(cfg, client.Options{
		Scheme: scheme,
	})
	if err != nil {
		return nil, err
	}
	return NewClientset(client), nil
}

func NewClientset(client client.Client) Clientset {
	return &clientSet{client: client}
}

// clienset for the extauth.solo.io/v1alpha1/v1alpha1 APIs
func (c *clientSet) ExtAuthConfigs() ExtAuthConfigClient {
	return NewExtAuthConfigClient(c.client)
}

// Reader knows how to read and list ExtAuthConfigs.
type ExtAuthConfigReader interface {
	// Get retrieves a ExtAuthConfig for the given object key
	GetExtAuthConfig(ctx context.Context, key client.ObjectKey) (*ExtAuthConfig, error)

	// List retrieves list of ExtAuthConfigs for a given namespace and list options.
	ListExtAuthConfig(ctx context.Context, opts ...client.ListOption) (*ExtAuthConfigList, error)
}

// ExtAuthConfigTransitionFunction instructs the ExtAuthConfigWriter how to transition between an existing
// ExtAuthConfig object and a desired on an Upsert
type ExtAuthConfigTransitionFunction func(existing, desired *ExtAuthConfig) error

// Writer knows how to create, delete, and update ExtAuthConfigs.
type ExtAuthConfigWriter interface {
	// Create saves the ExtAuthConfig object.
	CreateExtAuthConfig(ctx context.Context, obj *ExtAuthConfig, opts ...client.CreateOption) error

	// Delete deletes the ExtAuthConfig object.
	DeleteExtAuthConfig(ctx context.Context, key client.ObjectKey, opts ...client.DeleteOption) error

	// Update updates the given ExtAuthConfig object.
	UpdateExtAuthConfig(ctx context.Context, obj *ExtAuthConfig, opts ...client.UpdateOption) error

	// Patch patches the given ExtAuthConfig object.
	PatchExtAuthConfig(ctx context.Context, obj *ExtAuthConfig, patch client.Patch, opts ...client.PatchOption) error

	// DeleteAllOf deletes all ExtAuthConfig objects matching the given options.
	DeleteAllOfExtAuthConfig(ctx context.Context, opts ...client.DeleteAllOfOption) error

	// Create or Update the ExtAuthConfig object.
	UpsertExtAuthConfig(ctx context.Context, obj *ExtAuthConfig, transitionFuncs ...ExtAuthConfigTransitionFunction) error
}

// StatusWriter knows how to update status subresource of a ExtAuthConfig object.
type ExtAuthConfigStatusWriter interface {
	// Update updates the fields corresponding to the status subresource for the
	// given ExtAuthConfig object.
	UpdateExtAuthConfigStatus(ctx context.Context, obj *ExtAuthConfig, opts ...client.UpdateOption) error

	// Patch patches the given ExtAuthConfig object's subresource.
	PatchExtAuthConfigStatus(ctx context.Context, obj *ExtAuthConfig, patch client.Patch, opts ...client.PatchOption) error
}

// Client knows how to perform CRUD operations on ExtAuthConfigs.
type ExtAuthConfigClient interface {
	ExtAuthConfigReader
	ExtAuthConfigWriter
	ExtAuthConfigStatusWriter
}

type extAuthConfigClient struct {
	client client.Client
}

func NewExtAuthConfigClient(client client.Client) *extAuthConfigClient {
	return &extAuthConfigClient{client: client}
}

func (c *extAuthConfigClient) GetExtAuthConfig(ctx context.Context, key client.ObjectKey) (*ExtAuthConfig, error) {
	obj := &ExtAuthConfig{}
	if err := c.client.Get(ctx, key, obj); err != nil {
		return nil, err
	}
	return obj, nil
}

func (c *extAuthConfigClient) ListExtAuthConfig(ctx context.Context, opts ...client.ListOption) (*ExtAuthConfigList, error) {
	list := &ExtAuthConfigList{}
	if err := c.client.List(ctx, list, opts...); err != nil {
		return nil, err
	}
	return list, nil
}

func (c *extAuthConfigClient) CreateExtAuthConfig(ctx context.Context, obj *ExtAuthConfig, opts ...client.CreateOption) error {
	return c.client.Create(ctx, obj, opts...)
}

func (c *extAuthConfigClient) DeleteExtAuthConfig(ctx context.Context, key client.ObjectKey, opts ...client.DeleteOption) error {
	obj := &ExtAuthConfig{}
	obj.SetName(key.Name)
	obj.SetNamespace(key.Namespace)
	return c.client.Delete(ctx, obj, opts...)
}

func (c *extAuthConfigClient) UpdateExtAuthConfig(ctx context.Context, obj *ExtAuthConfig, opts ...client.UpdateOption) error {
	return c.client.Update(ctx, obj, opts...)
}

func (c *extAuthConfigClient) PatchExtAuthConfig(ctx context.Context, obj *ExtAuthConfig, patch client.Patch, opts ...client.PatchOption) error {
	return c.client.Patch(ctx, obj, patch, opts...)
}

func (c *extAuthConfigClient) DeleteAllOfExtAuthConfig(ctx context.Context, opts ...client.DeleteAllOfOption) error {
	obj := &ExtAuthConfig{}
	return c.client.DeleteAllOf(ctx, obj, opts...)
}

func (c *extAuthConfigClient) UpsertExtAuthConfig(ctx context.Context, obj *ExtAuthConfig, transitionFuncs ...ExtAuthConfigTransitionFunction) error {
	genericTxFunc := func(existing, desired runtime.Object) error {
		for _, txFunc := range transitionFuncs {
			if err := txFunc(existing.(*ExtAuthConfig), desired.(*ExtAuthConfig)); err != nil {
				return err
			}
		}
		return nil
	}
	_, err := controllerutils.Upsert(ctx, c.client, obj, genericTxFunc)
	return err
}

func (c *extAuthConfigClient) UpdateExtAuthConfigStatus(ctx context.Context, obj *ExtAuthConfig, opts ...client.UpdateOption) error {
	return c.client.Status().Update(ctx, obj, opts...)
}

func (c *extAuthConfigClient) PatchExtAuthConfigStatus(ctx context.Context, obj *ExtAuthConfig, patch client.Patch, opts ...client.PatchOption) error {
	return c.client.Status().Patch(ctx, obj, patch, opts...)
}

// Provides ExtAuthConfigClients for multiple clusters.
type MulticlusterExtAuthConfigClient interface {
	// Cluster returns a ExtAuthConfigClient for the given cluster
	Cluster(cluster string) (ExtAuthConfigClient, error)
}

type multiclusterExtAuthConfigClient struct {
	client multicluster.Client
}

func NewMulticlusterExtAuthConfigClient(client multicluster.Client) MulticlusterExtAuthConfigClient {
	return &multiclusterExtAuthConfigClient{client: client}
}

func (m *multiclusterExtAuthConfigClient) Cluster(cluster string) (ExtAuthConfigClient, error) {
	client, err := m.client.Cluster(cluster)
	if err != nil {
		return nil, err
	}
	return NewExtAuthConfigClient(client), nil
}
