// Code generated by skv2. DO NOT EDIT.

// Definitions for the Kubernetes types
package v1alpha1

import (
	. "github.com/solo-io/ext-auth-service/pkg/api/extauth.solo.io/v1alpha1/types"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +k8s:openapi-gen=true
// +kubebuilder:subresource:status

// GroupVersionKind for ExtAuthConfig
var ExtAuthConfigGVK = schema.GroupVersionKind{
	Group:   "extauth.solo.io",
	Version: "v1alpha1",
	Kind:    "ExtAuthConfig",
}

// ExtAuthConfig is the Schema for the extAuthConfig API
type ExtAuthConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ExtAuthConfigSpec   `json:"spec,omitempty"`
	Status ExtAuthConfigStatus `json:"status,omitempty"`
}

// GVK returns the GroupVersionKind associated with the resource type.
func (ExtAuthConfig) GVK() schema.GroupVersionKind {
	return ExtAuthConfigGVK
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// ExtAuthConfigList contains a list of ExtAuthConfig
type ExtAuthConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ExtAuthConfig `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ExtAuthConfig{}, &ExtAuthConfigList{})
}
