// Code generated by skv2. DO NOT EDIT.

// This file contains generated Deepcopy methods for extauth.solo.io/v1alpha1 resources

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// Generated Deepcopy methods for ExtAuthConfig

func (in *ExtAuthConfig) DeepCopyInto(out *ExtAuthConfig) {
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)

	// deepcopy spec
	in.Spec.DeepCopyInto(&out.Spec)
	// deepcopy status
	in.Status.DeepCopyInto(&out.Status)

	return
}

func (in *ExtAuthConfig) DeepCopy() *ExtAuthConfig {
	if in == nil {
		return nil
	}
	out := new(ExtAuthConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *ExtAuthConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ExtAuthConfigList) DeepCopyInto(out *ExtAuthConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExtAuthConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

func (in *ExtAuthConfigList) DeepCopy() *ExtAuthConfigList {
	if in == nil {
		return nil
	}
	out := new(ExtAuthConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *ExtAuthConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
